// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQFQdqJFAd2bHqaYqOVxZgNgsX02EzOcs',
    appId: '1:126806768391:web:ea1ef9001bd7e84883a3a2',
    messagingSenderId: '126806768391',
    projectId: 'whispermind-fd660',
    authDomain: 'whispermind-fd660.firebaseapp.com',
    storageBucket: 'whispermind-fd660.firebasestorage.app',
    measurementId: 'G-E6GD1BXCBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFaYWItlkC6b2gaGOaYVuCISgkROYab-g',
    appId: '1:126806768391:android:a3f95dc9edba2f9483a3a2',
    messagingSenderId: '126806768391',
    projectId: 'whispermind-fd660',
    storageBucket: 'whispermind-fd660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqDbnOKzgpC5dWa9dLCmchXaM39qjd_o',
    appId: '1:126806768391:ios:566f92b763d59ef783a3a2',
    messagingSenderId: '126806768391',
    projectId: 'whispermind-fd660',
    storageBucket: 'whispermind-fd660.firebasestorage.app',
    iosClientId: '126806768391-bohb06i3pf12o13b6ivmrdv6jc2br3ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.whispermind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLqDbnOKzgpC5dWa9dLCmchXaM39qjd_o',
    appId: '1:126806768391:ios:566f92b763d59ef783a3a2',
    messagingSenderId: '126806768391',
    projectId: 'whispermind-fd660',
    storageBucket: 'whispermind-fd660.firebasestorage.app',
    iosClientId: '126806768391-bohb06i3pf12o13b6ivmrdv6jc2br3ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.whispermind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQFQdqJFAd2bHqaYqOVxZgNgsX02EzOcs',
    appId: '1:126806768391:web:8e3c9f0410d1127583a3a2',
    messagingSenderId: '126806768391',
    projectId: 'whispermind-fd660',
    authDomain: 'whispermind-fd660.firebaseapp.com',
    storageBucket: 'whispermind-fd660.firebasestorage.app',
    measurementId: 'G-VQ8WKPS82B',
  );
}
